selftests/bpf: Factor out arena stream tests to own source
Prior commit [0] added arena tests to the existing streams tests. As kernel
arena code is not always compiled (only 64-bit), building streams tests in
test_progs fails for 32-bit systems:

progs/stream.c:136:21: error: incomplete definition of type 'struct bpf_arena'
  136 |         user_vm_start = ptr->user_vm_start;
      |                         ~~~^
.../include/vmlinux.h:34574:8: note: forward declaration of 'struct bpf_arena'
 34574 | struct bpf_arena;
       |        ^
progs/stream.c:170:21: error: incomplete definition of type 'struct bpf_arena'
  170 |         user_vm_start = ptr->user_vm_start;
      |                         ~~~^
.../include/vmlinux.h:34574:8: note: forward declaration of 'struct bpf_arena'
 34574 | struct bpf_arena;
       |        ^
2 errors generated.

Previous arena test code was mainly added as separate source files [1],
allowing either their temporary removal as a workaround or, ultimately,
exclusion via Makefile to build successfully. Follow the prior approach
by separating out arena-specific stream test sources.

0: 86f2225065be ("selftests/bpf: Add tests for arena fault reporting")
1: arena_spin_lock.c, arena_atomics.c, arena_htab.c, arena_htab_asm.c,
   arena_list.c, verifier_arena.c, verifier_arena_large.c

Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>