selftests/bpf: Fix printf output directive in test_xsk.c
Use the explicit 64-bit output directive '%llx' to avoid compile errors due
to possible integer truncation, seen with GCC 12.3 targeting 32-bit ARM:

prog_tests/test_xsk.c: In function ‘__receive_pkts’:
prog_tests/test_xsk.c:1050:88: error: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘u64’ {aka ‘long long unsigned int’} [-Werror=format=]
 1050 |                                 ksft_print_msg("[%s] received too many packets addr: %lx len %u\n",
      |                                                                                      ~~^
      |                                                                                        |
      |                                                                                        long unsigned int
      |                                                                                      %llx
 1051 |                                                __func__, addr, desc->len);
      |                                                          ~~~~
      |                                                          |
      |                                                          u64 {aka long long unsigned int}
prog_tests/test_xsk.c:18:
prog_tests/test_xsk.c:1056:31: error: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘u64’ {aka ‘long long unsigned int’} [-Werror=format=]
 1056 |                 print_verbose("Rx: addr: %lx len: %u options: %u pkt_nb: %u valid: %u\n",
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1057 |                               addr, desc->len, desc->options, pkt->pkt_nb, pkt->valid);
      |                               ~~~~
      |                               |
      |                               u64 {aka long long unsigned int}

Fixes: 697604492b64 ("selftests/xsk: add invalid descriptor test for multi-buffer")
Fixes: 2d2712caf44b ("selftests/xsk: print per packet info in verbose mode")
Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>