selftests/bpf: Fix task_work 32-bit compile errors
The sources include unnecessary headers, including "<string.h>", which
conflict with a typedef in "vmlinux.h" when compiled for 32-bit systems:

In file included from /usr/include/string.h:33:
In file included from /usr/lib/llvm-18/lib/clang/18/include/stddef.h:77:
/usr/lib/llvm-18/lib/clang/18/include/__stddef_size_t.h:18:23: error: typedef redefinition with different types ('unsigned long' vs '__kernel_size_t' (aka 'unsigned int'))
   18 | typedef __SIZE_TYPE__ size_t;
      |                       ^
.../tools/testing/selftests/bpf/tools/include/vmlinux.h:22723:25: note: previous definition is here
 22723 | typedef __kernel_size_t size_t;
       |                         ^
1 error generated.

The conflict arises because "vmlinux.h" reflects the 32-bit host kernel,
while "<string.h>" reflects the 64-bit BPF VM. Fix this by dropping the
latter include since they are unneeded anyway, as well as instances of
"<stdbool.h>" and "errno.h".

Fixes: 39fd74dfd5d2 ("selftests/bpf: BPF task work scheduling tests")
Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>