selftests/bpf: Fix printf output directive in xdp_metadata.c
Use the explicit 64-bit output directive '%llx' to avoid compile errors due
to possible integer truncation, seen with GCC 12.3 targeting 32-bit ARM:

xdp_metadata.c: In function ‘open_xsk’:
xdp_metadata.c:106:47: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘u64’ {aka ‘long unsigned int’} [-Werror=format=]
  106 |                 printf("%p: tx_desc[%d] -> %llx\n", xsk, i, addr);
      |                                            ~~~^             ~~~~
      |                                               |             |
      |                                               |             u64 {aka long unsigned int}
      |                                               long long unsigned int
      |                                            %lx
xdp_metadata.c:119:47: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘u64’ {aka ‘long unsigned int’} [-Werror=format=]
  119 |                 printf("%p: rx_desc[%d] -> %llx\n", xsk, i, addr);
      |                                            ~~~^             ~~~~
      |                                               |             |
      |                                               |             u64 {aka long unsigned int}
      |                                               long long unsigned int
      |                                            %lx

Fixes: e2a46d54d7a1 ("selftests/bpf: Verify xdp_metadata xdp->af_xdp path")
Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>