selftests/bpf: WORKAROUND compile error from missing _Bool in test_cpp.cpp
bpftool makes skeleton from test_core_extern.c, which includes <stdbool.h>
and uses 'bool' type. Generated test_core_extern.skel.h DOES NOT include
<stdbool.h> or use 'bool' type, rather uses standard C '_Bool' type. When
test_cpp.cpp includes test_core_extern.skel.h, g++ fail with error:

  In file included from test_cpp.cpp:9:
  test_core_extern.skel.h:45:17: error: '_Bool' does not name a type
     45 |                 _Bool CONFIG_BOOL;
        |                 ^~~~~

Signed-off-by: Tony Ambardar <Tony.Ambardar@gmail.com>