selftests/bpf: Fix printf output directive in map_tests
Explicitly use the unsigned 8-bit output directive '%hhu' to avoid compile
errors due to detection of a potential integer string truncation, as seen
with GCC 12.3 targeting 32-bit ARM:

map_tests/lpm_trie_map_batch_ops.c: In function ‘map_batch_update’:
map_tests/lpm_trie_map_batch_ops.c:35:47: error: ‘%d’ directive output may be truncated writing between 1 and 9 bytes into a region of size 6 [-Werror=format-truncation=]
   35 |                 snprintf(buff, 16, "192.168.1.%d", i + 1);
      |                                               ^~
map_tests/lpm_trie_map_batch_ops.c:35:36: note: directive argument in the range [1, 536870913]
   35 |                 snprintf(buff, 16, "192.168.1.%d", i + 1);
      |                                    ^~~~~~~~~~~~~~
map_tests/lpm_trie_map_batch_ops.c:35:17: note: ‘snprintf’ output between 12 and 20 bytes into a destination of size 16
   35 |                 snprintf(buff, 16, "192.168.1.%d", i + 1);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: e9bd8cbd970b ("bpf: selftests: Add tests for batched ops in LPM trie maps")
Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>