selftests/bpf: TEST changing vfs_link kprobe for 32-bit
In file included from progs/profiler3.c:6:
progs/profiler.inc.h:818:5: error: no member named '__unsupported__' in 'struct
pt_regs'
  818 | int BPF_KPROBE(kprobe__vfs_link,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  819 |                struct dentry* old_dentry, struct mnt_idmap *idmap,
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  820 |                struct inode* dir, struct dentry* new_dentry,
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  821 |                struct inode** delegated_inode)
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kodidev/linux/tools/testing/selftests/bpf/tools/include/bpf/bpf_tracing.h:
824:20: note: expanded from macro 'BPF_KPROBE'
  824 |         return ____##name(___bpf_kprobe_args(args));
    \
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~
/home/kodidev/linux/tools/testing/selftests/bpf/tools/include/bpf/bpf_tracing.h:
804:41: note: expanded from macro '___bpf_kprobe_args'
  804 | #define ___bpf_kprobe_args(args...)     ___bpf_apply(___bpf_kprobe_args,
 ___bpf_narg(args))(args)
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kodidev/linux/tools/testing/selftests/bpf/tools/include/bpf/bpf_helpers.h:
216:29: note: expanded from macro '___bpf_apply'
  216 | #define ___bpf_apply(fn, n) ___bpf_concat(fn, n)
      |                             ^
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/home/kodidev/linux/tools/testing/selftests/bpf/tools/include/bpf/bpf_tracing.h:800:88: note: expanded from macro '___bpf_kprobe_args5'
  800 | #define ___bpf_kprobe_args5(x, args...) ___bpf_kprobe_args4(args), (unsigned long long)PT_REGS_PARM5(ctx)
      |                                                                                        ^~~~~~~~~~~~~~~~~~
/home/kodidev/linux/tools/testing/selftests/bpf/tools/include/bpf/bpf_tracing.h:496:46: note: expanded from macro 'PT_REGS_PARM5'
  496 | #define PT_REGS_PARM5(x) (__PT_REGS_CAST(x)->__PT_PARM5_REG)
      |                           ~~~~~~~~~~~~~~~~~  ^
/home/kodidev/linux/tools/testing/selftests/bpf/tools/include/bpf/bpf_tracing.h:470:24: note: expanded from macro '__PT_PARM5_REG'
  470 | #define __PT_PARM5_REG __unsupported__
      |                        ^

Fixes: e299bcd4d16f ("selftests/bpf: Fix vfs_link kprobe definition")
Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>