selftests/bpf: Fix file_reader 32-bit compile errors
The sources include unnecessary "<string.h>" headers, which conflict with a
typedef in "vmlinux.h" when compiled for 32-bit systems:

In file included from progs/file_reader_fail.c:5:
In file included from /usr/include/string.h:33:
In file included from /usr/lib/llvm-21/lib/clang/21/include/stddef.h:93:
/usr/lib/llvm-21/lib/clang/21/include/__stddef_size_t.h:18:23: error:
      typedef redefinition with different types ('unsigned long' vs
      '__kernel_size_t' (aka 'unsigned int'))
   18 | typedef __SIZE_TYPE__ size_t;
      |                       ^
.../tools/testing/selftests/bpf/tools/include/vmlinux.h:22252:25: note:
      previous definition is here
 22252 | typedef __kernel_size_t size_t;
       |                         ^
1 error generated.

The conflict arises because "vmlinux.h" reflects the 32-bit host kernel,
while "<string.h>" reflects the 64-bit BPF VM. Fix this by dropping the
latter includes since they are unneeded anyway.

Sources also use pointer 'char *user_ptr', which evaluates to different
sizes in the BPF VM and a 32-bit userspace when mapped via skeleton, and
thus fails a build-time assertion:

In file included from .../prog_tests/file_reader.c:7:
./file_reader_fail.skel.h: In function ‘file_reader_fail__assert’:
./file_reader_fail.skel.h:1400:9: error: static assertion failed: "unexpected size of \'user_ptr\'"
 1400 |         _Static_assert(sizeof(s->bss->user_ptr) == 8, "unexpected size of 'user_ptr'");
      |         ^~~~~~~~~~~~~~

Again, fix by dropping the global pointer since it is unused.

Fixes: 29419364917c ("selftests/bpf: add file dynptr tests")
Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>